export const CHANGE_USE_BUMP = 'CHANGE_USE_BUMP';
export const CHANGE_USE_SHADOW = 'CHANGE_USE_SHADOW';
export const CHANGE_BUMP_HEIGHT = 'CHANGE_BUMP_HEIGHT';
export const CHANGE_SHADOW_POSITION = 'CHANGE_SHADOW_POSITION';
export const PANEL_READY = 'PANEL_READY';
